// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
WITH new_conversation AS(
    INSERT INTO conversations(initiator_id, type)
    VALUES ($2::uuid, $3::conversation_types)
    RETURNING id, type, name, initiator_id, created_at, updated_at
),
conversation_participants AS(
    INSERT INTO conversation_participants(conversation_id, user_id)
    SELECT nc.id,k.user_id
    FROM new_conversation nc,(SELECT unnest(ARRAY[$2::uuid, (SELECT u.id from users u where u.email=$1 LIMIT 1)]) AS user_id) k
    RETURNING conversation_id, user_id, joined_at, left_at, last_read
)
SELECT nc.id, nc.type, nc.name, nc.initiator_id, nc.created_at, nc.updated_at,
    jsonb_agg(
        jsonb_build_object('user_id',cp.user_id,
            'joined_at',cp.joined_at,
            'name',u.name,
            'email',u.email,
            'image',u.image
        )
    ) as participants
FROM new_conversation nc
JOIN conversation_participants cp ON nc.id=cp.conversation_id
LEFT JOIN users u ON cp.user_id = u.id
GROUP BY nc.id,nc.type,nc.name,nc.initiator_id,nc.created_at,nc.updated_at
`

type CreateConversationParams struct {
	Email       string
	InitiatorID uuid.UUID
	Type        ConversationTypes
}

type CreateConversationRow struct {
	ID           uuid.UUID
	Type         ConversationTypes
	Name         *string
	InitiatorID  uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Participants []byte
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (CreateConversationRow, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Email, arg.InitiatorID, arg.Type)
	var i CreateConversationRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.InitiatorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Participants,
	)
	return i, err
}
