// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
WITH new_conversation AS(
    INSERT INTO conversations(initiator_id, type)
    VALUES ($1::uuid, $2::text)
    RETURNING id, type, name, initiator_id, created_at, updated_at
),
conversation_participants AS(
    INSERT INTO conversation_participants(conversation_id, user_id)
    SELECT conversation_id, user_id
    FROM unnest(ARRAY[new_conversation.id, new_conversation.id]) AS conversation_id, unnest(ARRAY[$1::uuid, $3::uuid]) AS user_id
    RETURNING conversation_id, user_id, joined_at, left_at, last_read
)
SELECT new_conversation.id, new_conversation.type, new_conversation.name, new_conversation.initiator_id, new_conversation.created_at, new_conversation.updated_at, jsonb_agg(to_jsonb(conversation_participants.*)) AS participants
FROM new_conversation
JOIN conversation_participants ON new_conversation.id = conversation_participants.conversation_id
`

type CreateConversationParams struct {
	InitiatorID   uuid.UUID
	Type          string
	ParticipantID uuid.UUID
}

type CreateConversationRow struct {
	ID           uuid.UUID
	Type         ConversationTypes
	Name         *string
	InitiatorID  uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Participants []byte
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (CreateConversationRow, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.InitiatorID, arg.Type, arg.ParticipantID)
	var i CreateConversationRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.InitiatorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Participants,
	)
	return i, err
}
