// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    pubkey, name, os, client,registration_id, user_agent, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6,$7
)
RETURNING id, pubkey, name, registration_id, os, client, user_agent, user_id, last_seen, created_at, updated_at
`

type CreateDeviceParams struct {
	Pubkey         string
	Name           string
	Os             string
	Client         ClientType
	RegistrationID int32
	UserAgent      *string
	UserID         uuid.UUID
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.Pubkey,
		arg.Name,
		arg.Os,
		arg.Client,
		arg.RegistrationID,
		arg.UserAgent,
		arg.UserID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Name,
		&i.RegistrationID,
		&i.Os,
		&i.Client,
		&i.UserAgent,
		&i.UserID,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByPubkey = `-- name: GetDeviceByPubkey :one
SELECT id, pubkey, name, registration_id, os, client, user_agent, user_id, last_seen, created_at, updated_at FROM devices
WHERE pubkey = $1
LIMIT 1
`

func (q *Queries) GetDeviceByPubkey(ctx context.Context, pubkey string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByPubkey, pubkey)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Name,
		&i.RegistrationID,
		&i.Os,
		&i.Client,
		&i.UserAgent,
		&i.UserID,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevicesByUserId = `-- name: GetDevicesByUserId :many
SELECT id, pubkey, name, registration_id, os, client, user_agent, user_id, last_seen, created_at, updated_at FROM devices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDevicesByUserId(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Pubkey,
			&i.Name,
			&i.RegistrationID,
			&i.Os,
			&i.Client,
			&i.UserAgent,
			&i.UserID,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET name = $2, os = $3, client = $4, user_agent = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, pubkey, name, registration_id, os, client, user_agent, user_id, last_seen, created_at, updated_at
`

type UpdateDeviceParams struct {
	ID        uuid.UUID
	Name      string
	Os        string
	Client    ClientType
	UserAgent *string
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.Os,
		arg.Client,
		arg.UserAgent,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Name,
		&i.RegistrationID,
		&i.Os,
		&i.Client,
		&i.UserAgent,
		&i.UserID,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
