// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getKeybundle = `-- name: GetKeybundle :many
WITH user_devices AS (
    SELECT id,client_id
    FROM devices
    WHERE user_id = $1
),
signed_keys AS (
    SELECT sp.device_id,
        sp.key_id,
        sp.public_key,
        sp.signature
    FROM device_signed_prekeys sp
    WHERE sp.device_id IN (
            SELECT id
            FROM user_devices
        )
    ORDER BY sp.created_at DESC
    LIMIT 1
),
consumed_prekey AS (
    DELETE FROM device_prekeys
    WHERE (device_id, key_id) = (
            SELECT pk.device_id,
                pk.key_id
            FROM device_prekeys pk
                JOIN signed_keys sk ON sk.device_id = pk.device_id
            ORDER BY pk.created_at ASC,
                pk.key_id ASC
            LIMIT 1
        )
    RETURNING device_id,
        key_id,
        public_key
)
SELECT pk.device_id,
    ud.client_id,
    sk.key_id as signed_key_id,
    sk.public_key as signed_prekey,
    sk.signature as signature,
    pk.key_id as prekey_id,
    pk.public_key as prekey
FROM consumed_prekey pk
    JOIN signed_keys sk ON sk.device_id = pk.device_id
    JOIN user_devices ud ON ud.id = pk.device_id
`

type GetKeybundleRow struct {
	DeviceID     uuid.UUID
	ClientID     int32
	SignedKeyID  int32
	SignedPrekey string
	Signature    string
	PrekeyID     int32
	Prekey       string
}

func (q *Queries) GetKeybundle(ctx context.Context, userID uuid.UUID) ([]GetKeybundleRow, error) {
	rows, err := q.db.Query(ctx, getKeybundle, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKeybundleRow
	for rows.Next() {
		var i GetKeybundleRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.ClientID,
			&i.SignedKeyID,
			&i.SignedPrekey,
			&i.Signature,
			&i.PrekeyID,
			&i.Prekey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPreKeys = `-- name: InsertPreKeys :one
WITH signed_key AS (
    INSERT INTO device_signed_prekeys (device_id, key_id, public_key, signature)
    VALUES (
            $1::uuid,
            $2::int,
            $3::text,
            $4::text
        )
    ON CONFLICT (device_id, key_id) DO UPDATE
    SET public_key = EXCLUDED.public_key,
        signature = EXCLUDED.signature
    RETURNING device_id,
        key_id,
        public_key
),
prekeys AS (
    INSERT INTO device_prekeys(device_id, key_id, public_key)
    SELECT s.device_id,
        k.key_id,
        k.public_key
    FROM signed_key as s,
        (
            SELECT unnest($5::int []) as key_id,
                unnest($6::text []) as public_key
        ) as k
    ON CONFLICT (device_id, key_id) DO UPDATE
    SET public_key = EXCLUDED.public_key
    RETURNING device_id
)
SELECT count(*)
FROM prekeys
`

type InsertPreKeysParams struct {
	Deviceid    uuid.UUID
	Signedkeyid int32
	Signedkey   string
	Signature   string
	Prekeyids   []int32
	Prekeys     []string
}

func (q *Queries) InsertPreKeys(ctx context.Context, arg InsertPreKeysParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPreKeys,
		arg.Deviceid,
		arg.Signedkeyid,
		arg.Signedkey,
		arg.Signature,
		arg.Prekeyids,
		arg.Prekeys,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
