// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: magic_link_sessions.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const cleanupExpiredMagicLinks = `-- name: CleanupExpiredMagicLinks :exec
DELETE FROM magic_link_sessions
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) CleanupExpiredMagicLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredMagicLinks)
	return err
}

const createMagicLinkSession = `-- name: CreateMagicLinkSession :one
INSERT INTO magic_link_sessions (
    token, email, pubkey,registration_id,ip_address, user_agent, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6,$7
)
RETURNING id, token, email, registration_id, pubkey, ip_address, user_agent, attempts, status, expires_at, created_at, updated_at
`

type CreateMagicLinkSessionParams struct {
	Token          string
	Email          string
	Pubkey         string
	RegistrationID int32
	IpAddress      netip.Addr
	UserAgent      *string
	ExpiresAt      time.Time
}

func (q *Queries) CreateMagicLinkSession(ctx context.Context, arg CreateMagicLinkSessionParams) (MagicLinkSession, error) {
	row := q.db.QueryRow(ctx, createMagicLinkSession,
		arg.Token,
		arg.Email,
		arg.Pubkey,
		arg.RegistrationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i MagicLinkSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.RegistrationID,
		&i.Pubkey,
		&i.IpAddress,
		&i.UserAgent,
		&i.Attempts,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMagicLinkByToken = `-- name: DeleteMagicLinkByToken :exec
DELETE FROM magic_link_sessions
WHERE token = $1
`

func (q *Queries) DeleteMagicLinkByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteMagicLinkByToken, token)
	return err
}

const deleteMagicLinkSession = `-- name: DeleteMagicLinkSession :exec
DELETE FROM magic_link_sessions
WHERE id = $1
`

func (q *Queries) DeleteMagicLinkSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMagicLinkSession, id)
	return err
}

const expireOldMagicLinks = `-- name: ExpireOldMagicLinks :exec
UPDATE magic_link_sessions
SET status = 'expired'
WHERE expires_at < CURRENT_TIMESTAMP
  AND status = 'pending'
`

func (q *Queries) ExpireOldMagicLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldMagicLinks)
	return err
}

const getMagicLinkSessionByEmail = `-- name: GetMagicLinkSessionByEmail :many
SELECT id, token, email, registration_id, pubkey, ip_address, user_agent, attempts, status, expires_at, created_at, updated_at FROM magic_link_sessions
WHERE email = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMagicLinkSessionByEmail(ctx context.Context, email string) ([]MagicLinkSession, error) {
	rows, err := q.db.Query(ctx, getMagicLinkSessionByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MagicLinkSession
	for rows.Next() {
		var i MagicLinkSession
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Email,
			&i.RegistrationID,
			&i.Pubkey,
			&i.IpAddress,
			&i.UserAgent,
			&i.Attempts,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMagicLinkSessionByToken = `-- name: GetMagicLinkSessionByToken :one
SELECT id, token, email, registration_id, pubkey, ip_address, user_agent, attempts, status, expires_at, created_at, updated_at FROM magic_link_sessions
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetMagicLinkSessionByToken(ctx context.Context, token string) (MagicLinkSession, error) {
	row := q.db.QueryRow(ctx, getMagicLinkSessionByToken, token)
	var i MagicLinkSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.RegistrationID,
		&i.Pubkey,
		&i.IpAddress,
		&i.UserAgent,
		&i.Attempts,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingMagicLinkSession = `-- name: GetPendingMagicLinkSession :one
SELECT id, token, email, registration_id, pubkey, ip_address, user_agent, attempts, status, expires_at, created_at, updated_at FROM magic_link_sessions
WHERE email = $1
  AND status = 'pending'
  AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetPendingMagicLinkSession(ctx context.Context, email string) (MagicLinkSession, error) {
	row := q.db.QueryRow(ctx, getPendingMagicLinkSession, email)
	var i MagicLinkSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.RegistrationID,
		&i.Pubkey,
		&i.IpAddress,
		&i.UserAgent,
		&i.Attempts,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMagicLinkAsUsed = `-- name: MarkMagicLinkAsUsed :one
UPDATE magic_link_sessions
SET status = 'used'
WHERE token = $1
RETURNING id, token, email, registration_id, pubkey, ip_address, user_agent, attempts, status, expires_at, created_at, updated_at
`

func (q *Queries) MarkMagicLinkAsUsed(ctx context.Context, token string) (MagicLinkSession, error) {
	row := q.db.QueryRow(ctx, markMagicLinkAsUsed, token)
	var i MagicLinkSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.RegistrationID,
		&i.Pubkey,
		&i.IpAddress,
		&i.UserAgent,
		&i.Attempts,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeMagicLink = `-- name: RevokeMagicLink :exec
UPDATE magic_link_sessions
SET status = 'revoked', updated_at = CURRENT_TIMESTAMP
WHERE token = $1
`

func (q *Queries) RevokeMagicLink(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeMagicLink, token)
	return err
}

const updateMagicLinkSession = `-- name: UpdateMagicLinkSession :one
UPDATE magic_link_sessions
SET token = $2,
    attempts = $3,
    expires_at = $4
WHERE id = $1
RETURNING id, token, email, registration_id, pubkey, ip_address, user_agent, attempts, status, expires_at, created_at, updated_at
`

type UpdateMagicLinkSessionParams struct {
	ID        uuid.UUID
	Token     string
	Attempts  int16
	ExpiresAt time.Time
}

func (q *Queries) UpdateMagicLinkSession(ctx context.Context, arg UpdateMagicLinkSessionParams) (MagicLinkSession, error) {
	row := q.db.QueryRow(ctx, updateMagicLinkSession,
		arg.ID,
		arg.Token,
		arg.Attempts,
		arg.ExpiresAt,
	)
	var i MagicLinkSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.RegistrationID,
		&i.Pubkey,
		&i.IpAddress,
		&i.UserAgent,
		&i.Attempts,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMagicLinkStatus = `-- name: UpdateMagicLinkStatus :one
UPDATE magic_link_sessions
SET status = $2
WHERE id = $1
RETURNING id, token, email, registration_id, pubkey, ip_address, user_agent, attempts, status, expires_at, created_at, updated_at
`

type UpdateMagicLinkStatusParams struct {
	ID     uuid.UUID
	Status MagicLinkStatus
}

func (q *Queries) UpdateMagicLinkStatus(ctx context.Context, arg UpdateMagicLinkStatusParams) (MagicLinkSession, error) {
	row := q.db.QueryRow(ctx, updateMagicLinkStatus, arg.ID, arg.Status)
	var i MagicLinkSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.RegistrationID,
		&i.Pubkey,
		&i.IpAddress,
		&i.UserAgent,
		&i.Attempts,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
