// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages (conversation_id, sender_user_id, sender_device_id, sequence_id, content_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, conversation_id, sender_user_id, sender_device_id, sequence_id, content_type, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID
	SenderUserID   uuid.UUID
	SenderDeviceID uuid.UUID
	SequenceID     int32
	ContentType    string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderUserID,
		arg.SenderDeviceID,
		arg.SequenceID,
		arg.ContentType,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.SenderDeviceID,
		&i.SequenceID,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const createMessageEnvelope = `-- name: CreateMessageEnvelope :one
INSERT INTO message_envelopes (message_id, recipient_user_id, recipient_device_id, is_incoming, context)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, message_id, recipient_user_id, recipient_device_id, is_incoming, context, created_at
`

type CreateMessageEnvelopeParams struct {
	MessageID         uuid.UUID
	RecipientUserID   uuid.UUID
	RecipientDeviceID uuid.UUID
	IsIncoming        bool
	Context           string
}

func (q *Queries) CreateMessageEnvelope(ctx context.Context, arg CreateMessageEnvelopeParams) (MessageEnvelope, error) {
	row := q.db.QueryRow(ctx, createMessageEnvelope,
		arg.MessageID,
		arg.RecipientUserID,
		arg.RecipientDeviceID,
		arg.IsIncoming,
		arg.Context,
	)
	var i MessageEnvelope
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.RecipientUserID,
		&i.RecipientDeviceID,
		&i.IsIncoming,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}
