// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ClientType string

const (
	ClientTypeMobile  ClientType = "mobile"
	ClientTypeWeb     ClientType = "web"
	ClientTypeDesktop ClientType = "desktop"
)

func (e *ClientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientType(s)
	case string:
		*e = ClientType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientType: %T", src)
	}
	return nil
}

type NullClientType struct {
	ClientType ClientType
	Valid      bool // Valid is true if ClientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientType) Scan(value interface{}) error {
	if value == nil {
		ns.ClientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientType), nil
}

type MagicLinkStatus string

const (
	MagicLinkStatusPending MagicLinkStatus = "pending"
	MagicLinkStatusUsed    MagicLinkStatus = "used"
	MagicLinkStatusExpired MagicLinkStatus = "expired"
	MagicLinkStatusRevoked MagicLinkStatus = "revoked"
)

func (e *MagicLinkStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MagicLinkStatus(s)
	case string:
		*e = MagicLinkStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MagicLinkStatus: %T", src)
	}
	return nil
}

type NullMagicLinkStatus struct {
	MagicLinkStatus MagicLinkStatus
	Valid           bool // Valid is true if MagicLinkStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMagicLinkStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MagicLinkStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MagicLinkStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMagicLinkStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MagicLinkStatus), nil
}

type RecordKind string

const (
	RecordKindMessage            RecordKind = "message"
	RecordKindReaction           RecordKind = "reaction"
	RecordKindFile               RecordKind = "file"
	RecordKindSystem             RecordKind = "system"
	RecordKindMemberJoin         RecordKind = "member_join"
	RecordKindMemberLeave        RecordKind = "member_leave"
	RecordKindConversationRename RecordKind = "conversation_rename"
)

func (e *RecordKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordKind(s)
	case string:
		*e = RecordKind(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordKind: %T", src)
	}
	return nil
}

type NullRecordKind struct {
	RecordKind RecordKind
	Valid      bool // Valid is true if RecordKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordKind) Scan(value interface{}) error {
	if value == nil {
		ns.RecordKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordKind), nil
}

type Conversation struct {
	ID        uuid.UUID
	Kind      string
	Name      *string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ConversationParticipant struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
	JoinedAt       time.Time
}

type Device struct {
	ID             uuid.UUID
	Pubkey         string
	Name           string
	RegistrationID int32
	Os             string
	Client         ClientType
	UserAgent      *string
	UserID         uuid.UUID
	LastSeen       *time.Time
	CreatedAt      *time.Time
	UpdatedAt      *time.Time
}

type DevicePrekey struct {
	DeviceID  uuid.UUID
	KeyID     int32
	PublicKey string
	CreatedAt time.Time
}

type DeviceSignedPrekey struct {
	DeviceID  uuid.UUID
	KeyID     int32
	PublicKey string
	Signature string
	CreatedAt time.Time
}

type MagicLinkSession struct {
	ID             uuid.UUID
	Token          string
	Email          string
	RegistrationID int32
	Pubkey         string
	IpAddress      netip.Addr
	UserAgent      *string
	Attempts       int16
	Status         MagicLinkStatus
	ExpiresAt      time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Record struct {
	ID                uuid.UUID
	ConversationID    uuid.UUID
	Kind              RecordKind
	SenderID          *uuid.UUID
	CiphertextContent []byte
	RecipientDeviceID *uuid.UUID
	PlaintextContent  []byte
	Capabilities      []byte
	CreatedAt         time.Time
}

type User struct {
	ID         uuid.UUID
	Name       *string
	Email      string
	Image      *string
	Password   *string
	Ipkey      string
	Onboarding bool
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}
