// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (
    conversation_id, kind, sender_id, ciphertext_content,
    recipient_device_id, plaintext_content, capabilities
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, conversation_id, kind, sender_id, ciphertext_content, recipient_device_id, plaintext_content, capabilities, created_at
`

type CreateRecordParams struct {
	ConversationID    uuid.UUID
	Kind              RecordKind
	SenderID          *uuid.UUID
	CiphertextContent []byte
	RecipientDeviceID *uuid.UUID
	PlaintextContent  []byte
	Capabilities      []byte
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, createRecord,
		arg.ConversationID,
		arg.Kind,
		arg.SenderID,
		arg.CiphertextContent,
		arg.RecipientDeviceID,
		arg.PlaintextContent,
		arg.Capabilities,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Kind,
		&i.SenderID,
		&i.CiphertextContent,
		&i.RecipientDeviceID,
		&i.PlaintextContent,
		&i.Capabilities,
		&i.CreatedAt,
	)
	return i, err
}

const getRecordsByConversation = `-- name: GetRecordsByConversation :many
SELECT id, conversation_id, kind, sender_id, ciphertext_content, recipient_device_id, plaintext_content, capabilities, created_at FROM records
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetRecordsByConversationParams struct {
	ConversationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetRecordsByConversation(ctx context.Context, arg GetRecordsByConversationParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, getRecordsByConversation, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.SenderID,
			&i.CiphertextContent,
			&i.RecipientDeviceID,
			&i.PlaintextContent,
			&i.Capabilities,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordsByConversationSince = `-- name: GetRecordsByConversationSince :many
SELECT id, conversation_id, kind, sender_id, ciphertext_content, recipient_device_id, plaintext_content, capabilities, created_at FROM records
WHERE conversation_id = $1
  AND created_at > $2
ORDER BY created_at ASC
`

type GetRecordsByConversationSinceParams struct {
	ConversationID uuid.UUID
	CreatedAt      time.Time
}

func (q *Queries) GetRecordsByConversationSince(ctx context.Context, arg GetRecordsByConversationSinceParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, getRecordsByConversationSince, arg.ConversationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.SenderID,
			&i.CiphertextContent,
			&i.RecipientDeviceID,
			&i.PlaintextContent,
			&i.Capabilities,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordsForDevice = `-- name: GetRecordsForDevice :many
SELECT id, conversation_id, kind, sender_id, ciphertext_content, recipient_device_id, plaintext_content, capabilities, created_at FROM records
WHERE recipient_device_id = $1
   OR recipient_device_id IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type GetRecordsForDeviceParams struct {
	RecipientDeviceID *uuid.UUID
	Limit             int32
}

func (q *Queries) GetRecordsForDevice(ctx context.Context, arg GetRecordsForDeviceParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, getRecordsForDevice, arg.RecipientDeviceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.SenderID,
			&i.CiphertextContent,
			&i.RecipientDeviceID,
			&i.PlaintextContent,
			&i.Capabilities,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
