// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, ipkey
) VALUES (
    $1, $2
)
RETURNING id,email,name,image,created_at,onboarding
`

type CreateUserParams struct {
	Email string
	Ipkey string
}

type CreateUserRow struct {
	ID         uuid.UUID
	Email      string
	Name       *string
	Image      *string
	CreatedAt  *time.Time
	Onboarding bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Ipkey)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.Onboarding,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,email,name,image,created_at,onboarding FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID         uuid.UUID
	Email      string
	Name       *string
	Image      *string
	CreatedAt  *time.Time
	Onboarding bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.Onboarding,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id,email,name,image,created_at,onboarding FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIdRow struct {
	ID         uuid.UUID
	Email      string
	Name       *string
	Image      *string
	CreatedAt  *time.Time
	Onboarding bool
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.Onboarding,
	)
	return i, err
}

const onboardUser = `-- name: OnboardUser :one
UPDATE users
SET name=$2,
image=coalesce($4,image),
password=$3,
onboarding=False
WHERE email=$1 RETURNING id,email,name,image,created_at,onboarding
`

type OnboardUserParams struct {
	Email    string
	Name     *string
	Password *string
	Image    *string
}

type OnboardUserRow struct {
	ID         uuid.UUID
	Email      string
	Name       *string
	Image      *string
	CreatedAt  *time.Time
	Onboarding bool
}

func (q *Queries) OnboardUser(ctx context.Context, arg OnboardUserParams) (OnboardUserRow, error) {
	row := q.db.QueryRow(ctx, onboardUser,
		arg.Email,
		arg.Name,
		arg.Password,
		arg.Image,
	)
	var i OnboardUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.Onboarding,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = coalesce($1,name),
image = coalesce($2,image),
password = coalesce($3,password),
onboarding = coalesce($4,onboarding)
WHERE id = $5
RETURNING id,email,name,image,created_at,onboarding
`

type UpdateUserParams struct {
	Name       *string
	Image      *string
	Password   *string
	Onboarding *bool
	ID         uuid.UUID
}

type UpdateUserRow struct {
	ID         uuid.UUID
	Email      string
	Name       *string
	Image      *string
	CreatedAt  *time.Time
	Onboarding bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Image,
		arg.Password,
		arg.Onboarding,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.CreatedAt,
		&i.Onboarding,
	)
	return i, err
}
